### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by tgnr** [USSCltd/www_brute#1]
Any chance to see some updates for this?

Add: Ability to resume logging after a positive hit is found. (User would logout and refresh login page, then hit start button again to continue)

Issue: Positive hit when page nulls.

**Comment by USSCltd** [comment]
Yes. Why not.
But a bit later. I have not engough time meanwhile.

**Comment by tgnr** [comment]
Thank you sir.

**Comment by tgnr** [comment]
Issue: Sometimes password is injected into username. User has to refresh page and remove brute entry to start over.

Add: Option for user to select that a login attempt would execute after the page has completed loading 100%. (this would be possibly for websites with high latency, not sure how effective this could be)

Add: Option to skip attempting to login with passwords under a specified character count. 

Add: Option to play a sound notification when positive hit is found.

**Comment by trydni** [comment]
Hello,  Thank you very much sir for such a cool extension! excuse me for my English.

**Comment by s0i37** [comment]
> Hello, can you help me with the extension Brute, I would be very grateful if you reply Thank you! Can be in Brute do to he brute only password without user and user:password can be so do disable in expanding when not need username and need one password with brute. Great extension I liked it if you help will be great. Thank you very much sir for such a cool extension! excuse me for my English.

Здравствуйте.
Плагин умеет подбирать только пароли. Для этого вам нужно указать для login и password одно и тоже поле.

**Comment by USSCltd** [comment]
> Hello, can you help me with the extension Brute, I would be very grateful if you reply Thank you! Can be in Brute do to he brute only password without user and user:password can be so do disable in expanding when not need username and need one password with brute. Great extension I liked it if you help will be great. Thank you very much sir for such a cool extension! excuse me for my English.

Здравствуйте.
Плагин умеет подбирать пароль без указания логина. Для этого вам нужно указать для login и password одно и тоже поле.

**Comment by USSCltd** [comment]
> Issue: Sometimes password is injected into username. User has to refresh page and remove brute entry to start over.

Give me an example page please.

> Add: Option for user to select that a login attempt would execute after the page has completed loading 100%. (this would be possibly for websites with high latency, not sure how effective this could be)

Do you mean ajax-forms? It implements almost impossible, because this extension don't analyze js-code of target page. For attacking ajax-forms you may use just "sec" fields for specifing of waiting ajax-response.

> Add: Option to skip attempting to login with passwords under a specified character count.

You mean to implement additional filtration of specified list?

> Add: Option to play a sound notification when positive hit is found.

### +

> Add: Ability to resume logging after a positive hit is found. (User would logout and refresh login page, then hit start button again to continue)

### +

> Issue: Positive hit when page nulls.

Again, I need more information, preferably URL

**Comment by trydni** [comment]
> > Здравствуйте, вы можете помочь мне с расширением Brute, я был бы очень признателен, если вы ответите Спасибо! Можно в Brute сделать, чтобы он переборлял только пароль без пользователя и пользователя: пароль можно отключить в расширении, когда не нужно имя пользователя и нужен один пароль с перебором. Большое расширение мне понравилось, если ты поможешь, будет здорово. Большое спасибо, сэр, за такое классное расширение! извините за мой английский.
> 
> Здравствуйте.
> Плагин умеет подбирать пароль без указания логина. Для этого вам нужно указать логин и пароль.

Hello, I tried everything to not get Brutus brutal only the password because there are 3 clicks of the user, password and recognize submit. And I would like to Brutus only drove the password and clicked as in the picture.
![Брут1](https://user-images.githubusercontent.com/55932409/71547598-1ebfea00-29b3-11ea-8122-83a632f8389e.jpg)

**Comment by USSCltd** [comment]
> > > Здравствуйте, вы можете помочь мне с расширением Brute, я был бы очень признателен, если вы ответите Спасибо! Можно в Brute сделать, чтобы он переборлял только пароль без пользователя и пользователя: пароль можно отключить в расширении, когда не нужно имя пользователя и нужен один пароль с перебором. Большое расширение мне понравилось, если ты поможешь, будет здорово. Большое спасибо, сэр, за такое классное расширение! извините за мой английский.
> > 
> > 
> > Здравствуйте.
> > Плагин умеет подбирать пароль без указания логина. Для этого вам нужно указать логин и пароль.
> 
> Hello, I tried everything to not get Brutus brutal only the password because there are 3 clicks of the user, password and recognize submit. And I would like to Brutus only drove the password and clicked as in the picture.
> ![Брут1](https://user-images.githubusercontent.com/55932409/71547598-1ebfea00-29b3-11ea-8122-83a632f8389e.jpg)

Give me the URL where you have a troubles.

**Comment by trydni** [comment]
> > > > Я был бы очень признателен, если вы ответите Пароль можно отключить в расширении, когда не нужно имя пользователя и нужен один пароль с перебором. Мне было бы интересно. Большое спасибо, сэр, за такое классное расширение! извините за мой английский.
> > > 
> > > 
> > > Здравствуйте. 
> > > Плагин умеет подбирать пароль без указания логина. Для этого вам нужно указать логин и пароль.
> > 
> > 
> > Здравствуйте, я попробовал все, чтобы не получить Brutus брутальный только пароль, потому что есть 3 клика пользователя, пароль и распознавать отправить. И хотелось бы, чтобы Брут только загнал пароль и нажал как на картинке.
> > ![Брут1](https://user-images.githubusercontent.com/55932409/71547598-1ebfea00-29b3-11ea-8122-83a632f8389e.jpg)
> 
> Дайте мне URL, где у вас проблемы.

Here is the archive with Brutus and screen with an error yet finding the right password, it stops and a green bar appears with the passwords. Help edit Brutus to open folders in the network Thank you for your help sir
![Безымянный](https://user-images.githubusercontent.com/55932409/71598611-9418ef80-2b58-11ea-9a48-b38332dc207f.jpg)
[www_brute-master.zip](https://github.com/USSCltd/www_brute/files/4010861/www_brute-master.zip)

**Comment by USSCltd** [comment]
Your changes for bruteforcing one input field (password). But www_brute supports this. You just need to click twice by one input field and click the submit button. Also you need to specify one any username (it will never insert in login form but needs for working of www_brute)

**Comment by USSCltd** [comment]
+I added abbility to continuation of bruteforcing after finding creds.
+Also I added sound notification.
About positive hits it happens often on sites with difficult dynamic HTLM generation (like Twitter or Instagram). Their login forms rebuilds after typing of username/passwords therefore www_brute can't find them.

**Comment by si452772** [comment]
Здраствуйте! Могу ли я брутфорсить приложение vk.com? Я пробую на vk.com но результата нет. Правильный пароль и логин скрипт пропускает и нечего не происходит. Подскажите мне пожалуйста , это у меня проблема или все таки сайт vk.com?

**Comment by s0i37** [comment]
Здравствуйте. Vk.com использует captcha. Это будет не эффективно.
