### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by magnusoloughlin** [USSCltd/www_brute#2]
It's unclear how to use, please inform.

**Comment by USSCltd** [comment]
Look the demo https://www.youtube.com/watch?v=d5oEAw46SaI

**Comment by PsiPhiTheta** [comment]
How are you side-loading the source code into a chrome extension now that it's been removed from the Chrome web store? Manifest.json not valid when trying to load 

Edit: managed to fix the manifest.json that had a deprecated version

**Comment by hasnogaems** [comment]
> Edit: managed to fix the manifest.json that had a deprecated version

@PsiPhiTheta Can you teach me how to install it on chrome?

**Comment by PsiPhiTheta** [comment]
Unfort didn't pan out for me in the end

**Comment by s0i37** [comment]
See demo
